id = "a762448e-464c-43da-95b8-e49eb07814ed"
created_at = "2026-05-20T20:45:35.168842700+00:00"
title = "[audit-api] Require every ticket to participate in dependency graph"
state = "done"
component = "audit-api"
priority = "high"
risk_level = "medium"
spec_refs = "a6318461-3a06-4d6d-aabb-7e06c33f4e1b"
type = "tracker-improvement"
