id = "24baf686-38fd-417d-9528-bebc02a556d0"
created_at = "2026-05-16T19:05:20.970287700+00:00"
title = "doc-api"
state = "draft"
component = "doc-api"
scope = "public"
slug = "doc-api"
type = "specification"
