id = "b72b0a40-496e-43d0-a5b3-ec358d85802b"
created_at = "2026-04-12T18:36:25.155513100+00:00"
title = "[Board] ticket-api: Cleanup, file ops, reconciliation, claim deprecation"
state = "done"
priority = "high"
type = "tracker-improvement"
