id = "14df656e-cef2-470e-9530-ef760b6c462c"
created_at = "2026-05-16T21:15:34.265880100+00:00"
title = "[ticket-viewer][ticket-vscode] Surface the next-work workflow in frontends"
state = "new"
depends_on = ["07836f41-7fa5-4e41-8411-1c7cf8aeee75"]
type = "tracker-improvement"
